name: Execute actions for evaluation

on:
  workflow_dispatch:
    inputs:
      number:
        description: 'A number'
        required:  false
        default: 0
        type: number

jobs:
  evaluate-skip-step:
    runs-on: ubuntu-latest
    steps:
    - name: May skip check
      uses: takayukioda/actions/skip-step@0376ed1940ce7afdb50be515d1d24f76f056e1e6
      with:
        number: ${{ inputs.number }}
